### ISSUE TITLE
checking on mobile-portfolio

### ISSUE THREAD

**Issue by sheldonwafula** [Naledi-Dikgale/mobile-portfolio#5]
There are linters errors please fix.
The header section looks Beautiful.

**Comment by Naledi-Dikgale** [comment]
Correct flow of GitHub used.
there are some linter errors

**Comment by Tshepo45** [comment]
some image link breaking check and fix path

**Comment by fickryiman** [comment]
much better to choose one screen size as the default media query size, while the size of the other is put on media query, for example, desktop version min-width: 768px as the default.
